import type { Metadata } from 'next';
import { FoundationBeliefs, LanguagePillars } from '../../components/foundation-beliefs';
import { SiteFooter, SiteHeader } from '../../components/site-chrome';
import { foundation } from '../../lib/foundation';

export const metadata: Metadata = { title: 'About the Foundation | Evanko Foundation', description: 'Free language-learning tools, 106 active students, and a mission to expand access through volunteers, school onboarding, and custom curriculum.', alternates: { canonical: '/about' } };

export default function About() {
  return <div className="site-page">
    <SiteHeader currentPath="/about" />
    <main className="about">
      <section className="about__hero shell"><h1>Enriching lives,<br />one word at a time.</h1></section>
      <section className="shell about__mission"><p>The Evanko Foundation is a 501(c)(3) nonprofit dedicated to expanding access to language learning. We create, fund, and maintain free tools so more people can learn, communicate, and take part in the world around them.</p><p>Our language-learning software, FlashFluent, offers illustrated vocabulary and practical ways to study, match, and listen. We have 106 active students across three classes in San Gabriel Valley school districts. Our next priority is to make that access available to more teachers, schools, and learners.</p><p>While technology increasingly makes translation easier and more accessible, we reaffirm our belief in the economic importance of learning a language. The service, travel and hospitality industries depend on people who can communicate with customers, coworkers and communities every day, without technological friction.</p><p>And if technology eventually replaces the need for fluency at work, learning a language will still matter. The research is clear: it benefits our cognitive health, keeps the mind engaged, and gives us a deeper way to connect with family, other cultures, and the world around us. That is something no amount of artificial intelligence will ever change.</p></section>
      <section className="about__quote"><div className="shell"><blockquote>“In a world where social interaction is increasingly replaced by social media, AI and technology, the core human experiences of expression, conversation, and meaningful connection are becoming more important than ever for our <em>mental health</em>, <em>economic opportunity</em> and <em>quality of life</em>.”</blockquote><cite><strong>Kyle Evanko</strong><span>Founder</span></cite></div></section>
      <section className="shell about__transparency"><div><p className="eyebrow">About & transparency</p><h2>Built for the public good.</h2><p>The Evanko Foundation is a founder-led 501(c)(3) nonprofit. We create, fund, and maintain practical, free entry points into language learning because cost, time, geography, and confidence too often determine who gets the chance to begin.</p><p>FlashFluent is live in six languages. Donations help cover servers, hosting, software development, and language expansion. Most importantly, they help us expand access so more people have a useful place to begin.</p><p>The most valuable support is your time: tutoring and language review. We are also seeking volunteers to help onboard teachers and schools to FlashFluent and create custom curriculum that matches what those schools are teaching.</p><p><a className="text-link" href="/get-involved">Offer your skills <span>→</span></a> · <a className="text-link" href="/donate">Support wider access <span>→</span></a></p></div><dl><div><dt>Organization</dt><dd>The Evanko Foundation</dd></div><div><dt>Founder</dt><dd>Kyle Evanko</dd></div><div><dt>Federal status</dt><dd>501(c)(3) nonprofit</dd></div><div><dt>EIN</dt><dd>33-2430782</dd></div><div><dt>Address</dt><dd>24124 Decorah Rd<br />Diamond Bar, CA 91765</dd></div><div><dt>Teachers & schools</dt><dd><a href={"mailto:" + foundation.contacts.teachers}>{foundation.contacts.teachers}</a></dd></div><div><dt>Volunteers & partners</dt><dd><a href={"mailto:" + foundation.contacts.partnerships}>{foundation.contacts.partnerships}</a></dd></div><div><dt>Donations</dt><dd><a href={"mailto:" + foundation.contacts.donations}>{foundation.contacts.donations}</a></dd></div><div><dt>Contact Kyle</dt><dd><a href={"mailto:" + foundation.email}>{foundation.email}</a></dd></div></dl></section>
      <section className="shell about__mission-link"><a className="text-link" href="/mission">Read our mission <span>→</span></a></section>
      <FoundationBeliefs />
      <LanguagePillars />
    </main>
    <SiteFooter currentPath="/about" />
  </div>;
}
