const evidence = [
  { number: '40%', label: 'of people globally lack access to education in a language they speak and understand fluently.', title: 'Learning begins with understanding.', body: ['A lesson delivered in an unfamiliar language puts distance between a student and the material. It affects the simple things that make learning possible: following a lesson, asking a question, and showing what they know.', 'UNESCO’s guidance recommends a foundation in a language learners understand, with additional languages introduced deliberately and supported over time. The goal is not to choose between a home language and English. It is to make sure a student can understand the classroom in front of them.'], source: ['UNESCO, “Languages Matter: Global Guidance on Multilingual Education” (2025)', 'https://www.unesco.org/en/articles/new-unesco-report-calls-multilingual-education-unlock-learning-and-inclusion?hub=67098'], articles: [['Read: What early language access makes possible', '/articles/learning-early'], ['Read: Why free tools matter', '/articles/why-free-tools']] },
  { number: '22%', label: 'of online vacancies in an OECD study explicitly required English.', title: 'Language is part of the job.', body: ['In service, hospitality, support, travel, and remote work, communication is part of the work itself. It affects whether someone can apply, explain a problem, welcome a customer, or keep a relationship going.', 'The OECD’s analysis of vacancies across 27 EU countries and the United Kingdom found English explicitly requested in 22% of postings. Among manager and professional roles, roughly one in two postings asked for English. Language is not a guarantee of work, but it already shapes the first conversation between an employer and an applicant.'], source: ['OECD, “The Demand for Language Skills in the European Labour Market” (2023)', 'https://www.oecd.org/en/publications/the-demand-for-language-skills-in-the-european-labour-market_e1a5abe0-en.html'], articles: [['Read: The economics of bilingualism', '/articles/economics-of-bilingualism'], ['Read: What service language really means', '/articles/service-language']] },
  { number: '1 in 3', label: 'adults who wanted education or training cited cost as a barrier in OECD survey data.', title: 'Adult learning has to fit around life.', body: ['Work, family, transport, and limited time shape whether an adult can take a class. A recommendation to “learn a language” is incomplete when the course is expensive, far away, or scheduled during a shift.', 'OECD data shows schedule conflicts are the most common barrier for adults who want training but do not participate; cost is another major obstacle. Free, self-directed practice gives people a way to learn when they have a few minutes available.'], source: ['OECD, “Education at a Glance 2024: Adult Participation in Education and Training”', 'https://www.oecd.org/en/publications/education-at-a-glance-2024_c00cad36-en/full-report/to-what-extent-do-adults-participate-in-education-and-training_c2f90a06.html'], articles: [['Read: Why free tools matter', '/articles/why-free-tools'], ['Explore FlashFluent', '/projects']] },
  { number: '1 in 6', label: 'people globally reported loneliness between 2014 and 2023.', title: 'A conversation needs more than a translation.', body: ['Translation can be useful in a difficult moment. Shared language makes room for the rest of a relationship: a follow-up question, a joke, a correction, a story, and the confidence to keep talking when the conversation changes direction.', 'The World Health Organization now treats social connection as a public-health concern. A language barrier is one of the many things that can make it harder to ask, answer, and return to a conversation.'], source: ['World Health Organization, “From Loneliness to Social Connection” (2025)', 'https://www.who.int/groups/commission-on-social-connection/report'], articles: [['Read: Translation can help. It doesn’t connect us.', '/articles/translation-and-connection'], ['Read: The language of belonging', '/articles/language-of-belonging']] },
];

export function WhyLanguageContent({ includeProgram = true }: { includeProgram?: boolean }) {
  return <>
    <section className="why-language__thesis"><div className="shell"><p>Language access</p><h2>Language shapes our world and our opportunities.</h2><div><p>Language shapes the ordinary moments that determine participation: following a lesson, applying for a job, asking for help, meeting a neighbor, speaking with a customer, or joining a family conversation.</p><p>The Foundation makes free learning tools for people who need an approachable place to begin and a way to keep practicing at their own pace.</p></div></div></section>
    <LanguageAccessEvidence />
    {includeProgram && <section className="shell why-language__program"><p className="eyebrow">FlashFluent</p><h2>A free place to start.</h2><p>FlashFluent has six live language courses and more than 1,600 illustrated terms in each language. Study, Match, and Listen modes give learners different ways to practice. The Foundation created, funds, and maintains the program, which has 106 active students across three classes in San Gabriel Valley school districts.</p><a className="button button--primary button--cycle" href="/projects">Explore FlashFluent</a></section>}
  </>;
}

export function LanguageAccessEvidence() {
  return <section className="shell evidence-section" id="language-access-barriers"><div className="evidence-section__heading"><p className="eyebrow">The evidence</p><h2>Where language access breaks down.</h2></div><div className="evidence-list">{evidence.map((item, index) => <article className="evidence-card" key={item.title}><div className="evidence-card__stat"><span>0{index + 1}</span><strong>{item.number}</strong><p>{item.label}</p></div><div className="evidence-card__body"><h3>{item.title}</h3>{item.body.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}<a className="evidence-card__source" href={item.source[1]} target="_blank" rel="noreferrer">Source: {item.source[0]} ↗</a><div className="evidence-card__links">{item.articles.map(([label, href]) => <a href={href} key={href}>{label} <b>→</b></a>)}</div></div></article>)}</div></section>;
}
