import type { Metadata } from 'next';
import { AnimatedIcon } from '../../../components/animated-icon';
import { ReadingProgress } from '../../../components/article-reader';
import { SiteFooter, SiteHeader } from '../../../components/site-chrome';
import { foundation } from '../../../lib/foundation';

export const metadata: Metadata = { title: 'A 15-minute vocabulary routine | Evanko Foundation', description: 'An original teacher guide with a suggested vocabulary routine, worked example, adaptation notes, and a simple exit check.', alternates: { canonical: '/resources/teacher-guide' } };

const sections = [
  { id: 'prepare', heading: 'Choose a small goal', paragraphs: ['This is a suggested 15-minute vocabulary activity teachers can adapt.', 'Choose three to five terms in the language you are teaching. Decide whether the goal is recognition, listening, or speaking. For example: “By the end, students can connect these three terms with their meanings.”', 'Use FlashFluent or vocabulary cards. A shared classroom display can support a demonstration; individual devices are not required for every part of the suggested activity.'] },
  { id: 'routine', heading: 'Try the 15-minute routine', paragraphs: ['2 minutes · Set the goal. Introduce a small group of terms and tell students what they will practice. Keep the task narrow enough to explain in one sentence.', '3 minutes · Model the terms. Show each illustration, say or play its term, and explain the meaning. Model one response before asking students to work independently.', '4 minutes · Practice and recall. Try a short Match or Listen activity, then hide the answer and ask students to recall a term. Revisit difficult vocabulary together.', '3 minutes · Use the vocabulary. In pairs, have one student point to an image while the other names or identifies it. Swap roles. Add a familiar sentence pattern if it suits the group.', '3 minutes · Finish with an exit check. Show three terms again in a different order. Ask students to identify or say them independently and note what to revisit.'] },
  { id: 'example', heading: 'Worked example: everyday foods', paragraphs: ['Use apple, banana, and avocado as the example set. Select their equivalent terms in the course you are teaching; English labels are used here to explain the activity.', 'Demonstrate: show the apple image and model the target-language term. Point to the illustration while saying the word. Repeat for banana and avocado.', 'Practice: show all three pictures. Say a term and ask students to point to its image. Next, point to an image and invite a student to recall the term. Change the order so students practice the vocabulary rather than memorizing a position.', 'Use it: partners take turns naming an image or identifying the image their partner names. If the class is ready, add a familiar sentence pattern such as “I like ___,” adapted to the target language.', 'Check it: ask each student to identify or name the three terms without seeing the answers. Keep recognition and speaking separate in your notes: a student may recognize a term before feeling ready to say it.'] },
  { id: 'adapt', heading: 'Adapt the task to your students', paragraphs: ['If the vocabulary is new, begin with two or three terms. Leave a model visible during early practice and offer extra time. A student can point to an image before moving to a spoken answer.', 'If students are ready for more, add one new term, remove the visible answer, or ask for a short example sentence. Change one part of the task at a time so you can understand what is difficult.', 'If the classroom shares a device, use it for the demonstration and organize pair practice with cards, drawings, or spoken prompts. Choose a response format that fits the materials available.'] },
  { id: 'check', heading: 'Use a simple exit check', paragraphs: ['Ask three questions: Can the student identify the image when they hear the term? Can they recall the term when shown the image? Which word needs another visit?', 'Use these checks to decide what to revisit next time. Return to the terms in a later lesson to see what students remember and where more practice would help.'] },
  { id: 'feedback', heading: 'Share what was useful', paragraphs: ['Tell us which language and activity you tried, what was clear, and what needed adjustment. Keep feedback focused on the activity rather than including students’ personal information.', 'Contact teachers@evanko.co about the guide, getting your school started with FlashFluent, or custom curriculum that matches what you are teaching. Volunteer tutors and curriculum contributors are welcome. You can print this guide using your browser’s print menu.'] },
];

export default function TeacherGuide() {
  return <div className="site-page"><SiteHeader /><main className="article-page">
    <div className="content-shell article-hero"><a className="text-link" href="/articles">← All resources</a><div className="article-page__hero-grid"><div><p className="eyebrow">For teachers · Suggested activity</p><h1>A 15-minute vocabulary routine.</h1><p className="article-dek">A few terms, several ways to practice, and a useful exit check. Adapt the routine to your students.</p><p className="article-byline">Evanko Foundation · September 2026</p></div><div className="article-page__art"><AnimatedIcon path="teamwork.json" /></div></div></div>
    <div className="content-shell article-layout"><ReadingProgress sections={sections.map(section => [section.id, section.heading] as [string, string])} /><article className="article-body" id="article-body">{sections.map((section, index) => <section id={section.id} key={section.id}><h2><span>0{index + 1}</span>{section.heading}</h2>{section.paragraphs.map(p => <p key={p}>{p}</p>)}</section>)}<aside className="article-source"><strong>Try it or share feedback</strong><p><a href={foundation.learningUrl}>Open FlashFluent</a> · <a href={'mailto:' + foundation.contacts.teachers + '?subject=Teacher%20guide%20feedback'}>Contact our teacher team</a></p></aside></article></div>
  </main><SiteFooter /></div>;
}
