import type { Metadata } from 'next';
import { SiteFooter, SiteHeader } from '../../components/site-chrome';
import { foundation } from '../../lib/foundation';

export const metadata: Metadata = { title: 'Classroom impact | Evanko Foundation', description: 'We have 106 active students across three classes in San Gabriel Valley school districts. Learn about use of our resources and our goals for understanding progress.', alternates: { canonical: '/impact' } };

const updates = [
  { number: '106', label: 'active students across three classes.', title: 'Our active students are learning locally.', paragraphs: ['We have 106 active students across three classes in San Gabriel Valley school districts. FlashFluent gives these learners an accessible place to practice vocabulary and keep learning.', 'Our aim is to help students learn more efficiently by making useful learning resources more accessible.'], link: ['About the Foundation', '/about'] },
  { number: '3', label: 'classes in San Gabriel Valley school districts.', title: 'Help more classrooms get started.', paragraphs: ['Our next priority is access expansion: bringing FlashFluent to more teachers and schools. We are seeking volunteers to help educators get started with the software.', 'Volunteers can help create custom curriculum that matches what schools are teaching. Language reviewers and tutors can contribute their skills as we build more useful support for learners.'], link: ['Explore our work', '/projects'] },
  { number: '15 min', label: 'suggested vocabulary activity for teachers to adapt.', title: 'A useful classroom resource.', paragraphs: ['Our original teacher guide offers a short vocabulary routine, a worked example, adaptation notes, and an exit check. Teachers can adapt the terms, timing, and practice to fit their lessons.', 'The guide helps teachers choose a small goal, model vocabulary, try recall practice, and decide what to revisit. Educators can share feedback or offer curriculum experience to help us develop more resources.'], link: ['Use the teacher guide', '/resources/teacher-guide'] },
];
export default function Impact() {
  return <div className="site-page"><SiteHeader /><main className="why-language">
    <section className="shell why-language__hero impact-intro">
      <div className="impact-intro__copy"><p className="eyebrow">Active students · {foundation.updated}</p><h1>Learning starts<br />close to home.</h1><p>We have 106 active students across three classes in San Gabriel Valley school districts. Our goal is to help students learn more efficiently and make learning more accessible.</p><div className="why-language__hero-links"><a className="button button--primary button--cycle" href="/projects">Explore free learning</a><a className="text-link" href="/resources/teacher-guide">For teachers <span>→</span></a></div></div>
      <figure className="impact-intro__photo"><img src="/images/temple-city-school-district.webp" srcSet="/images/temple-city-school-district-400.webp 400w, /images/temple-city-school-district.webp 636w" sizes="(max-width: 588px) calc(100vw - 28px), (max-width: 760px) 560px, (max-width: 1200px) calc((100vw - 88px) * .4), 445px" width={636} height={632} loading="eager" fetchPriority="high" decoding="async" alt="Temple City Unified School District building with a community mural." /></figure>
    </section>
    <section className="why-language__thesis"><div className="shell"><p>San Gabriel Valley, California</p><h2>Three classrooms.<br />A practical place to begin.</h2><div><p>A small foundation can start with a concrete community and a useful goal. For us, that means free language-learning tools with active students in three local classes.</p><p>The next step is wider access: more languages, more schools, and learning resources that fit what teachers are already teaching.</p></div></div></section>
    <section className="shell evidence-section"><div className="evidence-section__heading"><p className="eyebrow">Program update</p><h2>The work behind the numbers.</h2></div><div className="evidence-list">{updates.map((item, index) => <article className="evidence-card" key={item.title}><div className="evidence-card__stat"><span>0{index + 1}</span><strong>{item.number}</strong><p>{item.label}</p></div><div className="evidence-card__body"><h3>{item.title}</h3>{item.paragraphs.map(p => <p key={p}>{p}</p>)}<div className="evidence-card__links"><a href={item.link[1]}>{item.link[0]} <b>→</b></a></div></div></article>)}</div></section>
    <section className="shell why-language__program"><p className="eyebrow">For educators & supporters</p><h2>Help shape the next step.</h2><p>Volunteer for tutoring or language review, help onboard teachers and schools, or contribute custom curriculum. Your time and knowledge can help make free learning more accessible.</p><div className="button-row"><a className="button button--primary button--cycle" href="/get-involved">Get involved <span aria-hidden="true">→</span></a><a className="text-link" href="/donate">Support the Foundation <span>→</span></a></div></section>
  </main><SiteFooter /></div>;
}
